project:
  type: book

number-depth: 3

execute:
  echo: false
  warning: false
  message: false

book:
  title: "Lifespan Development: A Psychological Perspective"
  author: "Martha Lally and Suzanne Valentine-French"
  date: today
  cover-image: lifespan_development_cover_4e_2022.png
  repo-url: https://github.com/nathalieyuen/lifespan-development-4e-2022
  page-footer:
    left: |
      Lifespan Development was written by Martha Lally and Suzanne Valentine-French. Quarto adaptation by C. Nathalie Yuen.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_heredity.qmd
    - 03_infancy.qmd
    - 04_early_childhood.qmd
    - 05_middle_late_childhood.qmd
    - 06_adolescence.qmd
    - 07_emerging_early_adult.qmd
    - 08_middle_adult.qmd
    - 09_late_adult.qmd
    - 10_death_dying.qmd
    - 11_oer_attribution.qmd

format:
  html:
    theme: cosmo
    cover-image: lifespan_development_4e_2022_cover.png

editor: visual


